In [126]:
import pandas as pd
import numpy as np
import datetime
pd.set_option('display.max_columns', None)

In [18]:
df = pd.read_csv("../data/clean_full.csv")

In [19]:
df

,datetime,GAWW-01,GAWW-02,GAWW-03,GAWW-04,GAWW-05,GAWW-07,Kalverstraat,GAAM-01-AlbertCuypstraat,GABM-01,GABM-02,GABM-03,GABM-04,GABM-05,GACM-01,GACM-02,GACM-03,GACM-04,GAVM-01-Vondelstraat,GAVM-02-Stadhouderskade,GAVM-03-VanEeghenstraat,GAVM-04-Emmalaan,GAVM-05-Amstelveenseweg,GAVM-06-Kattenlaan,GKS-01-Kalverstraat,GVCV-01,GVCV-03,GVCV-04,GVCV-05,GVCV-06,GVCV-07,GVCV-08,GABM-06,GADM-01,GAMM-01-Noord,GAMM-01-Zuid,GABW-01-K,GABW-02-B,GABW-03-D,GABW-04-H,GABW-05-Oost,GABW-06-West,GASZ-01,GASZ-02,CMSA-GAKH-01,CMSA-GAWW-11,CMSA-GAWW-12,CMSA-GAWW-13,CMSA-GAWW-14,CMSA-GAWW-15,CMSA-GAWW-16,CMSA-GAWW-17,CMSA-GAWW-19,CMSA-GAWW-20,CMSA-GAWW-21,CMSA-GAWW-22,CMSA-GAWW-23,CMSA-GAWW-24,GADM-01-total,GADM-01-zone0,GAMM-01-Noord-total,GAMM-01-Noord-zone0,GAMM-01-Zuid-total,GAMM-01-Zuid-zone0,CMSA-GAABM-02,CMSA-GAABM-03,CMSA-GAABM-04,CMSA-GAABM-05,GJEM-01,GJEM-02,GJEM-03,GJEM-04,cmsa_asb_s1_rol_zuid,cmsa_asb_s2s3_rol_zuid,cmsa_asb_s6s7_rol_zuid,cmsa_asb_s8_rol_zuid,GACTO-PL4-01,GANP-02,GANP-05-1,GANP-05-2,GANP-06,GANP-09,GANP-15,GANP-16,GANP-20
0,2020-07-30 16:45:00,378.0,150.0,183.0,57.0,207.0,318.0,NaN,267.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,290.0,515.0,90.0,130.0,515.0,143.0,1290.0,470.0,409.0,330.0,300.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-07-30 17:00:00,367.0,201.0,204.0,112.0,179.0,283.0,NaN,279.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,261.0,639.0,84.0,143.0,540.0,178.0,1218.0,594.0,358.0,598.0,383.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-07-30 17:15:00,338.0,170.0,170.0,119.0,208.0,259.0,NaN,189.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,260.0,581.0,103.0,89.0,649.0,208.0,1118.0,143.0,547.0,264.0,455.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-07-30 17:30:00,288.0,142.0,134.0,120.0,134.0,243.0,NaN,157.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,332.0,651.0,85.0,146.0,670.0,228.0,1152.0,478.0,489.0,687.0,391.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-07-30 17:45:00,274.0,177.0,207.0,96.0,181.0,227.0,NaN,102.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,213.0,670.0,69.0,118.0,627.0,204.0,1080.0,408.0,343.0,471.0,357.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50118,2022-01-03 18:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,32.0,31.0,162.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,4.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,41.0,46.0,17.0,11.0,20.0,9.0,13.0,34.0,13.0,50.0,134.0,72.0,24.0,50.0,20.0,8.0,NaN,NaN,NaN,NaN,0.0,2.0,2.0,5.0,NaN,NaN,NaN,NaN,12.0,26.0,26.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50119,2022-01-03 18:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,23.0,23.0,129.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,4.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,32.0,38.0,14.0,10.0,19.0,7.0,10.0,30.0,11.0,41.0,119.0,61.0,21.0,43.0,14.0,6.0,NaN,NaN,NaN,NaN,1.0,2.0,2.0,4.0,NaN,NaN,NaN,NaN,11.0,18.0,18.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50120,2022-01-03 18:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,18.0,16.0,98.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,3.0,1.0,2.0,2.0,1.0,1.0,NaN,NaN,26.0,27.0,11.0,7.0,16.0,6.0,8.0,21.0,9.0,32.0,96.0,47.0,15.0,35.0,10.0,4.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,4.0,NaN,NaN,NaN,NaN,10.0,11.0,12.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50121,2022-01-03 19:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,12.0,10.0,64.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,2.0,1.0,2.0,1.0,1.0,1.0,NaN,NaN,18.0,20.0,8.0,4.0,12.0,4.0,6.0,14.0,7.0,22.0,58.0,30.0,10.0,24.0,7.0,3.0,NaN,NaN,NaN,NaN,0.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,6.0,8.0,7.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50122,2022-01-03 19:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
df.describe()

,GAWW-01,GAWW-02,GAWW-03,GAWW-04,GAWW-05,GAWW-07,Kalverstraat,GAAM-01-AlbertCuypstraat,GABM-01,GABM-02,GABM-03,GABM-04,GABM-05,GACM-01,GACM-02,GACM-03,GACM-04,GAVM-01-Vondelstraat,GAVM-02-Stadhouderskade,GAVM-03-VanEeghenstraat,GAVM-04-Emmalaan,GAVM-05-Amstelveenseweg,GAVM-06-Kattenlaan,GKS-01-Kalverstraat,GVCV-01,GVCV-03,GVCV-04,GVCV-05,GVCV-06,GVCV-07,GVCV-08,GABM-06,GADM-01,GAMM-01-Noord,GAMM-01-Zuid,GABW-01-K,GABW-02-B,GABW-03-D,GABW-04-H,GABW-05-Oost,GABW-06-West,GASZ-01,GASZ-02,CMSA-GAKH-01,CMSA-GAWW-11,CMSA-GAWW-12,CMSA-GAWW-13,CMSA-GAWW-14,CMSA-GAWW-15,CMSA-GAWW-16,CMSA-GAWW-17,CMSA-GAWW-19,CMSA-GAWW-20,CMSA-GAWW-21,CMSA-GAWW-22,CMSA-GAWW-23,CMSA-GAWW-24,GADM-01-total,GADM-01-zone0,GAMM-01-Noord-total,GAMM-01-Noord-zone0,GAMM-01-Zuid-total,GAMM-01-Zuid-zone0,CMSA-GAABM-02,CMSA-GAABM-03,CMSA-GAABM-04,CMSA-GAABM-05,GJEM-01,GJEM-02,GJEM-03,GJEM-04,cmsa_asb_s1_rol_zuid,cmsa_asb_s2s3_rol_zuid,cmsa_asb_s6s7_rol_zuid,cmsa_asb_s8_rol_zuid,GACTO-PL4-01,GANP-02,GANP-05-1,GANP-05-2,GANP-06,GANP-09,GANP-15,GANP-16,GANP-20
count,22043.000000,22057.000000,20743.000000,21245.000000,21394.000000,21573.000000,1794.000000,44806.000000,18705.000000,20164.000000,19721.000000,20363.000000,20241.000000,45618.000000,46153.000000,45483.000000,45647.000000,1211.000000,44983.000000,1156.000000,1183.00000,45177.000000,1196.000000,21607.000000,44288.000000,45577.000000,47008.000000,44930.000000,41955.000000,42450.000000,39478.000000,11494.000000,7676.0,6355.0,6355.0,28450.000000,28452.000000,28452.000000,28450.000000,28452.000000,28451.000000,2593.000000,2595.000000,25525.000000,25525.000000,25525.000000,25525.000000,25525.000000,25525.000000,25525.000000,25418.000000,25525.000000,25525.000000,25525.000000,25525.000000,25525.000000,25525.000000,25525.000000,25051.000000,745.000000,745.000000,745.000000,745.000000,21033.000000,21034.000000,21034.000000,21033.000000,6038.000000,6166.000000,6158.000000,6165.000000,19898.000000,19898.000000,19898.000000,19898.000000,13737.0,8463.000000,8464.000000,8465.000000,8465.000000,8465.000000,8465.000000,8465.000000,8465.000000
mean,65.829742,64.201433,33.095888,22.431396,33.590867,46.387846,108.345039,81.837946,53.583053,105.896796,102.243142,91.749644,80.994813,166.497304,169.840465,77.853462,202.179048,130.703551,127.640131,64.176471,71.91716,168.148106,98.540134,127.720692,73.638457,117.515106,129.310947,78.809103,42.895769,51.176561,19.922058,5.350009,0.0,0.0,0.0,1.870088,1.406615,0.891748,1.262953,0.993568,1.081263,68.060162,136.929094,290.673614,149.722037,170.631773,117.793026,59.776650,121.413046,129.546876,111.396019,93.174691,149.146680,329.957610,115.441058,44.050186,114.414300,50.464290,14.524370,0.825503,0.511409,3.445638,0.798658,2.818000,2.102834,8.850861,9.205487,7.675555,14.934155,25.184151,1.863098,10.617047,43.918132,41.468741,11.125641,0.0,11.750089,2.370747,4.700177,5.941996,2.472298,4.625635,2.745422,2.306438
std,78.230432,85.600923,57.892364,30.682854,64.574959,51.312261,141.920776,132.989087,61.209409,119.608559,117.246005,106.565349,93.097258,263.985962,255.800529,105.616376,240.174511,95.092937,151.691495,44.196550,55.39237,184.726274,71.782651,218.332548,101.703565,107.661189,121.074475,82.297422,76.369021,85.655395,55.881152,10.712708,0.0,0.0,0.0,1.683213,1.257795,0.879403,1.148196,0.965283,1.005121,74.208328,145.912095,399.542730,159.547282,188.140599,155.737567,74.941086,181.750956,175.883165,123.386190,101.084950,147.929504,341.122725,110.484382,47.492818,113.178886,77.342829,26.809174,1.292719,0.584469,10.407300,1.394979,4.734283,6.278829,13.120435,11.431848,26.695429,38.151504,51.401702,7.424380,9.495824,55.093319,52.453674,15.575086,0.0,30.632408,7.016654,13.104103,16.620786,7.028347,13.314382,7.983105,6.407875
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,15.000000,11.000000,1.000000,5.000000,3.000000,10.000000,19.000000,1.000000,1.000000,8.000000,10.000000,15.000000,15.000000,5.000000,7.000000,7.000000,20.000000,35.000000,3.000000,25.000000,23.00000,7.000000,27.000000,8.000000,1.000000,27.000000,31.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,17.000000,27.000000,25.000000,15.000000,17.000000,16.000000,20.000000,20.000000,18.000000,31.000000,42.000000,21.000000,12.000000,23.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,14.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,40.000000,32.000000,14.000000,15.000000,14.000000,30.000000,42.000000,20.000000,29.000000,49.000000,45.000000,44.000000,40.000000,35.000000,42.000000,33.000000,102.000000,124.000000,49.000000,57.000000,68.00000,81.000000,99.000000,30.000000,37.000000,97.000000,102.000000,60.000000,11.000000,16.000000,0.000000,0.000000,0.0,0.0,0.0,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,48.000000,94.000000,73.000000,92.000000,93.000000,45.000000,37.000000,44.000000,59.000000,60.000000,50.000000,95.000000,205.000000,82.000000,26.000000,74.000000,15.000000,4.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,3.000000,6.000000,0.000000,0.000000,0.000000,0.000000,12.000000,26.000000,25.000000,12.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,87.000000,85.000000,33.000000,28.000000,31.000000,66.000000,149.250000,98.000000,92.000000,187.000000,177.000000,146.000000,128.000000,204.000000,225.000000,106.000000,309.000000,208.000000,224.000000,93.000000,105.00000,308.000000,151.000000,134.000000,107.000000,177.000000,193.000000,121.000000,45.000000,64.000000,16.000000,6.000000,0.0,0.0,0.0,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,125.000000,247.500000,469.000000,229.000000,262.000000,170.000000,81.000000,149.000000,170.000000,174.000000,145.000000,237.000000,540.000000,183.000000,65.000000,181.000000,68.000000,18.000000,1.000000,1.000000,2.000000,1.000000,4.000000,2.000000,11.000000,14.000000,7.000000,19.000000,18.000000,0.000000,15.000000,55.000000,53.000000,15.000000,0.0,4.000000,1.000000,1.000000,2.000000,1.000000,0.000000,0.000000,0.000000
max,626.000000,749.000000,668.000000,586.000000,907.000000,454.000000,729.000000,890.000000,376.000000,534.000000,574.000000,585.000000,495.000000,1498.000000,1438.000000,875.000000,1699.000000,412.000000,962.000000,225.000000,387.00000,907.000000,468.000000,1666.000000,1305.000000,945.000000,1205.000000,900.000000,795.000000,975.000000,840.000000,136.000000,0.0,0.0,0.0,13.000000,14.000000,8.000000,8.000000,11.000000,7.000000,295.000000,620.000000,2178.000000,1250.000000,1284.000000,974.000000,1833.000000,1614.000000,1738.000000,964.000000,827.000000,1056.000000,3992.000000,1365.000000,423.000000,722.000000,1151.000000,618.000000,10.000000,4.000000,99.000000,10.000000,105.000000,149.000000,139.000000,183.000000,743.000000,568.000000,476.000000,128.000000,386.000000,955.000000,1162.000000,680.000000,0.0,284.000000,93.000000,133.000000,215.000000,88.000000,139.000000,75.000000,88.000000

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50123 entries, 0 to 50122
Data columns (total 85 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   datetime                  50123 non-null  object
 1   GAWW-01                   22043 non-null  float64
 2   GAWW-02                   22057 non-null  float64
 3   GAWW-03                   20743 non-null  float64
 4   GAWW-04                   21245 non-null  float64
 5   GAWW-05                   21394 non-null  float64
 6   GAWW-07                   21573 non-null  float64
 7   Kalverstraat              1794 non-null   float64
 8   GAAM-01-AlbertCuypstraat  44806 non-null  float64
 9   GABM-01                   18705 non-null  float64
 10  GABM-02                   20164 non-null  float64
 11  GABM-03                   19721 non-null  float64
 12  GABM-04                   20363 non-null  float64
 13  GABM-05                   20241 non-null  float64
 14  GACM-01                   45618 non-null  float64
 15  GACM-02                   46153 non-null  float64
 16  GACM-03                   45483 non-null  float64
 17  GACM-04                   45647 non-null  float64
 18  GAVM-01-Vondelstraat      1211 non-null   float64
 19  GAVM-02-Stadhouderskade   44983 non-null  float64
 20  GAVM-03-VanEeghenstraat   1156 non-null   float64
 21  GAVM-04-Emmalaan          1183 non-null   float64
 22  GAVM-05-Amstelveenseweg   45177 non-null  float64
 23  GAVM-06-Kattenlaan        1196 non-null   float64
 24  GKS-01-Kalverstraat       21607 non-null  float64
 25  GVCV-01                   44288 non-null  float64
 26  GVCV-03                   45577 non-null  float64
 27  GVCV-04                   47008 non-null  float64
 28  GVCV-05                   44930 non-null  float64
 29  GVCV-06                   41955 non-null  float64
 30  GVCV-07                   42450 non-null  float64
 31  GVCV-08                   39478 non-null  float64
 32  GABM-06                   11494 non-null  float64
 33  GADM-01                   7676 non-null   float64
 34  GAMM-01-Noord             6355 non-null   float64
 35  GAMM-01-Zuid              6355 non-null   float64
 36  GABW-01-K                 28450 non-null  float64
 37  GABW-02-B                 28452 non-null  float64
 38  GABW-03-D                 28452 non-null  float64
 39  GABW-04-H                 28450 non-null  float64
 40  GABW-05-Oost              28452 non-null  float64
 41  GABW-06-West              28451 non-null  float64
 42  GASZ-01                   2593 non-null   float64
 43  GASZ-02                   2595 non-null   float64
 44  CMSA-GAKH-01              25525 non-null  float64
 45  CMSA-GAWW-11              25525 non-null  float64
 46  CMSA-GAWW-12              25525 non-null  float64
 47  CMSA-GAWW-13              25525 non-null  float64
 48  CMSA-GAWW-14              25525 non-null  float64
 49  CMSA-GAWW-15              25525 non-null  float64
 50  CMSA-GAWW-16              25525 non-null  float64
 51  CMSA-GAWW-17              25418 non-null  float64
 52  CMSA-GAWW-19              25525 non-null  float64
 53  CMSA-GAWW-20              25525 non-null  float64
 54  CMSA-GAWW-21              25525 non-null  float64
 55  CMSA-GAWW-22              25525 non-null  float64
 56  CMSA-GAWW-23              25525 non-null  float64
 57  CMSA-GAWW-24              25525 non-null  float64
 58  GADM-01-total             25525 non-null  float64
 59  GADM-01-zone0             25051 non-null  float64
 60  GAMM-01-Noord-total       745 non-null    float64
 61  GAMM-01-Noord-zone0       745 non-null    float64
 62  GAMM-01-Zuid-total        745 non-null    float64
 63  GAMM-01-Zuid-zone0        745 non-null    float64
 64  CMSA-GAABM-02             21033 non-null  float64
 65  CMSA-GAABM-03             21034 non-null  float64
 66  CMSA-GAABM-04             21034 non-null  float64
 67  CMSA-GAABM-05             21033 non-null  float64
 68  GJEM-01                   6038 non-null   float64
 69  GJEM-02                   6166 non-null   float64
 70  GJEM-03                   6158 non-null   float64
 71  GJEM-04                   6165 non-null   float64
 72  cmsa_asb_s1_rol_zuid      19898 non-null  float64
 73  cmsa_asb_s2s3_rol_zuid    19898 non-null  float64
 74  cmsa_asb_s6s7_rol_zuid    19898 non-null  float64
 75  cmsa_asb_s8_rol_zuid      19898 non-null  float64
 76  GACTO-PL4-01              13737 non-null  float64
 77  GANP-02                   8463 non-null   float64
 78  GANP-05-1                 8464 non-null   float64
 79  GANP-05-2                 8465 non-null   float64
 80  GANP-06                   8465 non-null   float64
 81  GANP-09                   8465 non-null   float64
 82  GANP-15                   8465 non-null   float64
 83  GANP-16                   8465 non-null   float64
 84  GANP-20                   8465 non-null   float64
dtypes: float64(84), object(1)
memory usage: 32.5+ MB

In [322]:
df_small = df[['datetime', 'GAWW-01', 'GAWW-02', 'GAWW-04', 
               'CMSA-GAWW-11', 'CMSA-GAWW-12', 'CMSA-GAWW-14', 'CMSA-GAWW-17']]

In [323]:
df_small['CMSA-GAWW-11'].update(df_small.pop('GAWW-01'))
df_small['CMSA-GAWW-12'].update(df_small.pop('GAWW-02'))
df_small['CMSA-GAWW-14'].update(df_small.pop('GAWW-04'))

/Users/chielingyueh/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3444: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)

In [325]:
df_small = df_small.rename(columns={"CMSA-GAWW-11": "GAWW-11", "CMSA-GAWW-12": "GAWW-12", 
                                    "CMSA-GAWW-14": "GAWW-14", "CMSA-GAWW-17": "GAWW-17",})

In [326]:
df_small.isna().sum()

datetime        0
GAWW-11      2555
GAWW-12      2541
GAWW-14      3353
GAWW-17     24705
dtype: int64

In [327]:
df_small.describe()

            GAWW-11       GAWW-12       GAWW-14       GAWW-17
count  47568.000000  47582.000000  46770.000000  25418.000000
mean     110.846367    121.295175     42.812786    111.396019
std      135.074486    158.749986     61.954718    123.386190
min        0.000000      0.000000      0.000000      0.000000
25%       21.000000     17.000000     11.000000     20.000000
50%       58.000000     51.000000     23.000000     60.000000
75%      150.000000    170.000000     52.000000    174.000000
max     1250.000000   1284.000000   1833.000000    964.000000

In [328]:
df_small = df_small.set_index('datetime')

In [329]:
df_small

                     GAWW-11  GAWW-12  GAWW-14  GAWW-17
datetime
2020-07-30 16:45:00    378.0    150.0     57.0      NaN
2020-07-30 17:00:00    367.0    201.0    112.0      NaN
2020-07-30 17:15:00    338.0    170.0    119.0      NaN
2020-07-30 17:30:00    288.0    142.0    120.0      NaN
2020-07-30 17:45:00    274.0    177.0     96.0      NaN
...                      ...      ...      ...      ...
2022-01-03 18:15:00     46.0     17.0     20.0     34.0
2022-01-03 18:30:00     38.0     14.0     19.0     30.0
2022-01-03 18:45:00     27.0     11.0     16.0     21.0
2022-01-03 19:00:00     20.0      8.0     12.0     14.0
2022-01-03 19:15:00      0.0      0.0      0.0      0.0

[50123 rows x 4 columns]

In [330]:
df_small.isna().sum()

GAWW-11     2555
GAWW-12     2541
GAWW-14     3353
GAWW-17    24705
dtype: int64

In [331]:
df_small_fill_zero = df_small.fillna(0)

In [335]:
df_small_fill_zero = df_small_fill_zero.drop(columns=['GAWW-17'])

In [336]:
df_small_fill_zero

                     GAWW-11  GAWW-12  GAWW-14
datetime
2020-07-30 16:45:00    378.0    150.0     57.0
2020-07-30 17:00:00    367.0    201.0    112.0
2020-07-30 17:15:00    338.0    170.0    119.0
2020-07-30 17:30:00    288.0    142.0    120.0
2020-07-30 17:45:00    274.0    177.0     96.0
...                      ...      ...      ...
2022-01-03 18:15:00     46.0     17.0     20.0
2022-01-03 18:30:00     38.0     14.0     19.0
2022-01-03 18:45:00     27.0     11.0     16.0
2022-01-03 19:00:00     20.0      8.0     12.0
2022-01-03 19:15:00      0.0      0.0      0.0

[50123 rows x 3 columns]

In [337]:
df_small_fill_zero = df_small_fill_zero[(df_small_fill_zero.index > '2020-08-31 23:45:00') & 
                                        (df_small_fill_zero.index < '2022-01-02 00:00:00')]

In [338]:
df_small_fill_zero.to_csv("/Users/chielingyueh/Downloads/cmsa_small_fill_zero.csv")

In [300]:
def fill_nan(df_subset, column):
    df_subset.index = pd.DatetimeIndex(df_subset.index)
    
    for index, row in df_subset.iterrows():
        if index > pd.to_datetime('2020-08-31 23:45:00') and index < pd.to_datetime('2022-01-02 00:00:00'):
            if np.isnan(row[column]):
                
                seven = index - datetime.timedelta(days=7)
                fourteen = index - datetime.timedelta(days=14)
                
                seven_count = df_subset[df_subset.index == str(seven)].values[0][0]
                fourteen_count = df_subset[df_subset.index == str(fourteen)].values[0][0]
                
                if np.isnan(seven_count):
                    avg = fourteen_count
                elif np.isnan(fourteen_count):
                    avg = seven_count
                else:
                    avg = ((seven_count + fourteen_count)/2).round(0)
                row[column] = avg
            else:
                continue
    return df_subset

In [270]:
df_small.columns

Index(['GAWW-11', 'GAWW-12', 'GAWW-14', 'GAWW-17'], dtype='object')

In [311]:
df_temp_11 = fill_nan(df_small[['GAWW-11']], 'GAWW-11')
df_temp_12 = fill_nan(df_small[['GAWW-12']], 'GAWW-12')
df_temp_14 = fill_nan(df_small[['GAWW-14']], 'GAWW-14')
df_temp_17 = fill_nan(df_small[['GAWW-17']], 'GAWW-17')

In [312]:
df_temp_11 = df_temp_11[(df_temp_11.index > '2020-08-31 23:45:00') & (df_temp_11.index < '2022-01-02 00:00:00')]
df_temp_12 = df_temp_12[(df_temp_12.index > '2020-08-31 23:45:00') & (df_temp_12.index < '2022-01-02 00:00:00')]
df_temp_14 = df_temp_14[(df_temp_14.index > '2020-08-31 23:45:00') & (df_temp_14.index < '2022-01-02 00:00:00')]
df_temp_17 = df_temp_17[(df_temp_17.index > '2021-04-12 23:45:00') & (df_temp_17.index < '2022-01-02 00:00:00')]

In [313]:
print(df_temp_11.isna().sum())
print(df_temp_12.isna().sum())
print(df_temp_14.isna().sum())
print(df_temp_17.isna().sum())

GAWW-11    0
dtype: int64
GAWW-12    0
dtype: int64
GAWW-14    0
dtype: int64
GAWW-17    0
dtype: int64

In [319]:
df_small_filled = pd.concat([df_temp_11, df_temp_12, df_temp_14, df_temp_17], axis=1)

In [339]:
df_small_filled = df_small_filled.drop(columns=['GAWW-17'])

In [340]:
df_small_filled

                     GAWW-11  GAWW-12  GAWW-14
datetime
2020-09-01 00:00:00    104.0    113.0     32.0
2020-09-01 00:15:00     73.0    109.0     30.0
2020-09-01 00:30:00     84.0     88.0     27.0
2020-09-01 00:45:00     95.0     99.0     26.0
2020-09-01 01:00:00     63.0     84.0     43.0
...                      ...      ...      ...
2022-01-01 22:45:00     48.0     22.0     21.0
2022-01-01 23:00:00     28.0     16.0     21.0
2022-01-01 23:15:00     27.0     26.0     21.0
2022-01-01 23:30:00     29.0     19.0     15.0
2022-01-01 23:45:00     25.0     14.0     19.0

[46848 rows x 3 columns]

In [341]:
df_small_filled.to_csv('/Users/chielingyueh/Downloads/cmsa_small_filled.csv')